# Generated by Django 4.2.11 on 2024-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSignIn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sncuser',
            name='user_password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='sncuser',
            name='user_name',
            field=models.CharField(default='randomSNCuser', max_length=100),
        ),
    ]
